package uk.gov.justice.digital.hmpps.electronicmonitoringcrimematchingapi.repository.crimeBatch

import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Repository
import uk.gov.justice.digital.hmpps.electronicmonitoringcrimematchingapi.model.entity.CrimeBatchEmailAttachmentIngestionError
import java.util.UUID

@Repository
interface CrimeBatchEmailAttachmentIngestionErrorRepository : JpaRepository<CrimeBatchEmailAttachmentIngestionError, UUID>
