package uk.gov.justice.digital.hmpps.electronicmonitoringcrimematchingapi.repository.crimeBatch

import org.springframework.data.domain.Page
import org.springframework.data.domain.Pageable
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.data.jpa.repository.Query
import org.springframework.stereotype.Repository
import uk.gov.justice.digital.hmpps.electronicmonitoringcrimematchingapi.model.entity.CrimeVersion
import uk.gov.justice.digital.hmpps.electronicmonitoringcrimematchingapi.model.enums.CrimeType
import uk.gov.justice.digital.hmpps.electronicmonitoringcrimematchingapi.repository.projection.CrimeVersionSummaryProjection
import java.time.Instant
import java.util.Optional
import java.util.UUID

@Repository
interface CrimeVersionRepository : JpaRepository<CrimeVersion, UUID> {
  fun findByCrimeIdAndCrimeTypeIdAndCrimeDateTimeFromAndCrimeDateTimeToAndEastingAndNorthingAndLatitudeAndLongitudeAndCrimeText(
    crimeId: UUID,
    crimeTypeId: CrimeType,
    crimeDateTimeFrom: Instant,
    crimeDateTimeTo: Instant,
    easting: Double?,
    northing: Double?,
    latitude: Double?,
    longitude: Double?,
    crimeText: String,
  ): Optional<CrimeVersion>

  /*
    Each row represents an ingestion event linking a crime_version to the crime_batch it was received in.

    Important distinction to prevent confusion regarding "versions" terminology:

    • crime_version (database entity)
      Stored snapshot of a crime's attributes.
      A new record is created only when those attributes change.

    • versionLabel (derived by this query)
      A chronological label used by the UI to describe how the crime has evolved across batch ingestions.

    This query reconstructs the ingestion timeline for each crime
    (grouped by police_force_area and crime_reference) and determines:

    • whether the current ingestion represents a new derived version
    • whether the ingestion is a duplicate of the previous crime state
    • which fields changed compared with the previous derived version

    Version labels are generated by comparing each row with the previous ingestion using SQL window functions.
   */
  @Query(
    value = """
    WITH versioned_crimes AS (
    
      -- 1. Build the ingestion timeline for each crime and capture previous values
      --
      -- Each row represents an ingestion event linking a stored crime_version snapshot to a crime_batch.
      -- For each crime (grouped by police_force_area + crime_reference) the ingestion history is ordered chronologically.
      -- LAG() allows us to compare the current snapshot with the previously ingested snapshot.
      SELECT
        cv.id AS crimeVersionId,
        c.crime_reference AS crimeReference,
        c.police_force_area AS policeForceArea,
    
        cv.crime_type_id AS crimeTypeId,
        cv.crime_date_time_from AS crimeDateTimeFrom,
        cv.crime_date_time_to AS crimeDateTimeTo,
    
        cv.easting,
        cv.northing,
        cv.latitude,
        cv.longitude,
    
        cb.batch_id AS batchId,
        cb.created_at AS ingestionDateTime,
    
        -- Capture values from the previous ingestion in the timeline
        LAG(cv.crime_type_id) OVER crime_versions AS previous_crime_type,
        LAG(cv.crime_date_time_from) OVER crime_versions AS previous_date_from,
        LAG(cv.crime_date_time_to) OVER crime_versions AS previous_date_to,
    
        LAG(cv.easting) OVER crime_versions AS previous_easting,
        LAG(cv.northing) OVER crime_versions AS previous_northing,
        LAG(cv.latitude) OVER crime_versions AS previous_latitude,
        LAG(cv.longitude) OVER crime_versions AS previous_longitude
    
      FROM crime_batch_crime_version cbcv
    
      JOIN crime_batch cb
        ON cb.id = cbcv.crime_batch_id
    
      JOIN crime_version cv
        ON cv.id = cbcv.crime_version_id
    
      JOIN crime c
        ON c.id = cv.crime_id
    
      -- Partial crime reference search
      -- LOWER() for case-insensitive matching
      -- '%' before and after the search term allows matching anywhere in the string
      WHERE LOWER(c.crime_reference) LIKE '%' || LOWER(:crimeReference) || '%'
    
      WINDOW crime_versions AS (
        PARTITION BY c.police_force_area, c.crime_reference
        ORDER BY cb.created_at
      )
    ),
    
    updates AS (
    
      -- 2. Determine whether the current ingestion represents a new derived version or a duplicate of the previous snapshot.
    
      -- version_increment values
      -- 1 → first ingestion OR snapshot values changed
      -- 0 → duplicate ingestion of the same snapshot
      SELECT *,
    
        CASE
    
          -- First row becomes the first derived version
          WHEN previous_crime_type IS NULL THEN 1
    
          -- Detect changes in any version-controlled fields
          WHEN previous_crime_type IS DISTINCT FROM crimeTypeId
            OR previous_date_from IS DISTINCT FROM crimeDateTimeFrom
            OR previous_date_to IS DISTINCT FROM crimeDateTimeTo
            OR previous_easting IS DISTINCT FROM easting
            OR previous_northing IS DISTINCT FROM northing
            OR previous_latitude IS DISTINCT FROM latitude
            OR previous_longitude IS DISTINCT FROM longitude
    
          THEN 1
    
          -- Otherwise this ingestion is a duplicate snapshot
          ELSE 0
    
        END AS version_increment
    
      FROM versioned_crimes
    ),
    
    version_numbers AS (
    
      -- 3. Generate version numbers based on cumulative increments.
      --
      -- Each time version_increment = 1, the version number increases.
      SELECT *,
    
        SUM(version_increment) OVER (
          PARTITION BY policeForceArea, crimeReference
          ORDER BY ingestionDateTime
        ) AS version_number
    
      FROM updates
    ),
    
    versioned AS (
    
      -- 4. Determine the maximum derived version for each crime timeline
      SELECT *,
    
        MAX(version_number) OVER (
          PARTITION BY policeForceArea, crimeReference
        ) AS max_version_number
    
      FROM version_numbers
    ),
    
    derived_versions AS (
    
      -- 5. Extract only derived versions (exclude duplicates)
      --
      -- Updates in the UI should describe what changed when a new derived version was created.
      -- Duplicates are ingestions of the same snapshot and should not affect update comparison.
      SELECT *
      FROM versioned
      WHERE version_increment = 1
    ),
    
    derived_versions_with_prev AS (
    
      -- 6. Capture values from the previous derived version
      SELECT
        *,
    
        LAG(crimeTypeId) OVER derived_crime_versions AS previous_derived_crime_type,
        LAG(crimeDateTimeFrom) OVER derived_crime_versions AS previous_derived_date_from,
        LAG(crimeDateTimeTo) OVER derived_crime_versions AS previous_derived_date_to,
    
        LAG(easting) OVER derived_crime_versions AS previous_derived_easting,
        LAG(northing) OVER derived_crime_versions AS previous_derived_northing,
        LAG(latitude) OVER derived_crime_versions AS previous_derived_latitude,
        LAG(longitude) OVER derived_crime_versions AS previous_derived_longitude
    
      FROM derived_versions
    
      WINDOW derived_crime_versions AS (
        PARTITION BY policeForceArea, crimeReference
        ORDER BY ingestionDateTime
      )
    ),
    
    versioned_with_previous_derived AS (
    
      -- 7. Join previous derived values back to the full ingestion timeline
      --
      -- Join on (policeForceArea, crimeReference, version_number) so that:
      -- every derived version row has a previous_derived_* set (except version 1)
      -- duplicates retain their own row but do not participate in update comparison
      SELECT
        v.*,
    
        d.previous_derived_crime_type,
        d.previous_derived_date_from,
        d.previous_derived_date_to,
    
        d.previous_derived_easting,
        d.previous_derived_northing,
        d.previous_derived_latitude,
        d.previous_derived_longitude
    
      FROM versioned v
      LEFT JOIN derived_versions_with_prev d
        ON d.policeForceArea = v.policeForceArea
        AND d.crimeReference = v.crimeReference
        AND d.version_number = v.version_number
    )
    
    SELECT
      crimeVersionId,
      crimeReference,
      policeForceArea,
      crimeTypeId,
      crimeDateTimeFrom,
      batchId,
      ingestionDateTime,
    
      -- Version label displayed in UI
      CASE
    
        -- Duplicate ingestion
        WHEN version_increment = 0
          THEN 'Duplicate'
    
        -- Only one derived version exists
        WHEN max_version_number = 1
          THEN 'Latest version'
    
        -- Latest derived version when multiple versions exist
        WHEN version_number = max_version_number
          THEN 'Latest version'
    
        -- Historical derived versions
        ELSE 'Version ' || version_number
    
      END AS versionLabel,
    
      -- Determine which fields changed compared to the previous derived version
      --
      -- Rules:
      -- • If there is only one derived version, updates should be 'N/A'
      -- • If the row is a duplicate, updates should be 'None'
      -- • If the row is the first derived version but there are later versions, updates should be 'N/A'
      -- • Otherwise show what changed between this derived version and the previous derived version
      CASE
    
        -- Duplicate snapshot
        WHEN version_increment = 0
          THEN 'None'
    
        -- Only one derived version exists
        WHEN max_version_number = 1
          THEN 'N/A'
    
        -- First derived version in a multi-version timeline
        WHEN version_number = 1
          THEN 'N/A'
    
        ELSE concat_ws(', ',
    
          CASE
            WHEN previous_derived_crime_type IS DISTINCT FROM crimeTypeId
            THEN 'Crime type'
          END,
    
          CASE
            WHEN previous_derived_date_from IS DISTINCT FROM crimeDateTimeFrom
            THEN 'Crime date'
          END,
    
          CASE
            WHEN previous_derived_date_to IS DISTINCT FROM crimeDateTimeTo
            THEN 'Crime time'
          END,
    
          CASE
            WHEN previous_derived_easting IS DISTINCT FROM easting
              OR previous_derived_northing IS DISTINCT FROM northing
              OR previous_derived_latitude IS DISTINCT FROM latitude
              OR previous_derived_longitude IS DISTINCT FROM longitude
            THEN 'Crime location'
          END
    
        )
    
      END AS updates,
    
      -- Determine whether matching results exist
      EXISTS (
        SELECT 1
        FROM crime_matching_result cmr
        WHERE cmr.crime_version_id = crimeVersionId
      ) AS matched
    
    FROM versioned_with_previous_derived
    
    -- Results returned newest first for the UI table
    ORDER BY ingestionDateTime DESC
    """,

    countQuery = """
     SELECT COUNT(*)
     FROM crime_batch_crime_version cbcv
     JOIN crime_batch cb ON cb.id = cbcv.crime_batch_id
     JOIN crime_version cv ON cv.id = cbcv.crime_version_id
     JOIN crime c ON c.id = cv.crime_id
     WHERE (:crimeReference IS NULL
            OR LOWER(c.crime_reference) LIKE '%' || LOWER(:crimeReference) || '%')
    """,

    nativeQuery = true,
  )
  fun findCrimeVersionsByCrimeReference(
    crimeReference: String?,
    pageable: Pageable,
  ): Page<CrimeVersionSummaryProjection>
}
