package uk.gov.justice.digital.hmpps.electronicmonitoringcrimematchingapi.repository.crimeBatch

import org.springframework.data.domain.Page
import org.springframework.data.domain.Pageable
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.data.jpa.repository.Query
import org.springframework.stereotype.Repository
import uk.gov.justice.digital.hmpps.electronicmonitoringcrimematchingapi.model.entity.CrimeVersion
import uk.gov.justice.digital.hmpps.electronicmonitoringcrimematchingapi.model.enums.CrimeType
import uk.gov.justice.digital.hmpps.electronicmonitoringcrimematchingapi.repository.projection.CrimeVersionSummaryProjection
import java.time.LocalDateTime
import java.util.Optional
import java.util.UUID

@Repository
interface CrimeVersionRepository : JpaRepository<CrimeVersion, UUID> {
  fun findByCrimeIdAndCrimeTypeIdAndCrimeDateTimeFromAndCrimeDateTimeToAndEastingAndNorthingAndLatitudeAndLongitudeAndCrimeText(
    crimeId: UUID,
    crimeTypeId: CrimeType,
    crimeDateTimeFrom: LocalDateTime,
    crimeDateTimeTo: LocalDateTime,
    easting: Double?,
    northing: Double?,
    latitude: Double?,
    longitude: Double?,
    crimeText: String,
  ): Optional<CrimeVersion>

  /*
    Each row represents an ingestion event linking a crime_version to the crime_batch it was received in.

    Important distinction to prevent confusion regarding "versions" terminology:

    • crime_version (database entity)
      Stored snapshot of a crime's attributes.
      A new record is created only when those attributes change.

    • versionLabel (derived by this query)
      A chronological label used by the UI to describe how the crime has evolved across batch ingestions.

    This query reconstructs the ingestion timeline for each crime
    (grouped by police_force_area and crime_reference) and determines:

    • whether the current ingestion represents a new derived version
    • whether the ingestion is a duplicate of the previous crime state
    • which fields changed compared with the previous ingestion

    Version labels are generated by comparing each row with the
    previous ingestion using SQL window functions.
  */
  @Query(
    value = """
      WITH versioned_crimes AS (

        -- 1. Build the ingestion timeline for each crime and capture previous values
        -- Each row represents an ingestion event linking a stored crime_version snapshot to a crime_batch.
        -- For each crime (grouped by police_force_area + crime_reference) the ingestion history is ordered chronologically.
        -- LAG() allows us to look at values from the previous ingestion of the same crime so we can compare the current snapshot with the previously ingested snapshot.
        SELECT
          cv.id AS crimeVersionId,
          c.crime_reference AS crimeReference,
          c.police_force_area AS policeForceArea,
      
          cv.crime_type_id AS crimeTypeId,
          cv.crime_date_time_from AS crimeDateTimeFrom,
          cv.crime_date_time_to AS crimeDateTimeTo,
      
          cv.easting,
          cv.northing,
          cv.latitude,
          cv.longitude,
      
          cb.batch_id AS batchId,
          cb.created_at AS ingestionDateTime,
      
          -- Previous values captured using LAG()
          -- LAG(column) returns the value from the previous row in the crimes ingestion timeline.
          -- These previous values allow us to detect whether the current ingested snapshot differs from the previously ingested snapshot.
          LAG(cv.crime_type_id) OVER crime_versions AS prev_crime_type,
          LAG(cv.crime_date_time_from) OVER crime_versions AS prev_date_from,
          LAG(cv.crime_date_time_to) OVER crime_versions AS prev_date_to,
      
          LAG(cv.easting) OVER crime_versions AS prev_easting,
          LAG(cv.northing) OVER crime_versions AS prev_northing,
          LAG(cv.latitude) OVER crime_versions AS prev_latitude,
          LAG(cv.longitude) OVER crime_versions AS prev_longitude
      
        FROM crime_batch_crime_version cbcv
      
        JOIN crime_batch cb
          ON cb.id = cbcv.crime_batch_id
      
        JOIN crime_version cv
          ON cv.id = cbcv.crime_version_id
      
        JOIN crime c
          ON c.id = cv.crime_id
      
        -- Partial crime reference search.
        -- LOWER() for case-insensitive searching.
        -- '%' matches any number of characters.
        WHERE LOWER(c.crime_reference) LIKE LOWER(:crimeReference) || '%'
      
        -- WINDOW defines how PostgreSQL decides what the "previous row" is when LAG() is used.

        -- LAG() needs two things:
        -- 1) Which rows belong together
        -- 2) The order of those rows
        
        -- PARTITION BY
        -- Groups rows by (police_force_area, crime_reference).
        -- Each crime therefore has its own independent sequence of ingested crime_version snapshots.
        -- So LAG() only compares rows within the same crime timeline.
        
        -- ORDER BY
        -- Sorts those rows by the ingestion timestamp (cb.created_at).
        -- This creates a chronological order of ingested crimes.
        WINDOW crime_versions AS (
          PARTITION BY c.police_force_area, c.crime_reference
          ORDER BY cb.created_at
        )
      ),
      
      updates AS (
      
        -- 2. Detect whether the current ingestion represents a new derived version label or a duplicate snapshot
        
        -- version_increment values:
        --  1 -> first ingestion OR snapshot values changed
        -- 0 -> duplicate ingestion of the same snapshot state
        SELECT *,
      
          CASE
      
            -- First row in each timeline becomes Version 1
            WHEN prev_crime_type IS NULL THEN 1
      
            -- Detect changes in any of the version-controlled fields.
            WHEN prev_crime_type IS DISTINCT FROM crimeTypeId
              OR prev_date_from IS DISTINCT FROM crimeDateTimeFrom
              OR prev_date_to IS DISTINCT FROM crimeDateTimeTo
              OR prev_easting IS DISTINCT FROM easting
              OR prev_northing IS DISTINCT FROM northing
              OR prev_latitude IS DISTINCT FROM latitude
              OR prev_longitude IS DISTINCT FROM longitude
      
            THEN 1
      
            -- Otherwise the ingestion is a duplicate
            ELSE 0
      
          END AS version_increment
      
        FROM versioned_crimes
      ),
      
      versioned AS (
      
        -- 3. Generate version numbers
        
        -- We use a cumulative SUM of version_increment.
        -- Because version_increment is 1 when a new derived version occurs, the SUM increments version numbers used in the UI.
        SELECT *,
      
          SUM(version_increment) OVER (
            PARTITION BY policeForceArea, crimeReference
            ORDER BY ingestionDateTime
          ) AS version_number
      
        FROM updates
      )
      
      SELECT
        crimeVersionId,
        crimeReference,
        policeForceArea,
        crimeTypeId,
        crimeDateTimeFrom,
        batchId,
        ingestionDateTime,
      
        -- Version label displayed in UI
        CASE
          WHEN version_increment = 0 THEN 'Duplicate'
          ELSE 'Version ' || version_number
        END AS versionLabel,
      
        -- Determine which fields changed compared to the previous row
        
        -- concat_ws() builds a comma-separated list of changes.
        -- Only fields that changed are included which is why this is used not CONCAT().
        -- Example - "Crime type, Crime location"
        CASE
          WHEN version_increment = 0 THEN 'None'
          ELSE concat_ws(', ',
      
            CASE
              WHEN prev_crime_type IS DISTINCT FROM crimeTypeId
              THEN 'Crime type'
            END,
      
            CASE
              WHEN prev_date_from IS DISTINCT FROM crimeDateTimeFrom
              THEN 'Crime date'
            END,
      
            CASE
              WHEN prev_date_to IS DISTINCT FROM crimeDateTimeTo
              THEN 'Crime time'
            END,
      
            CASE
              WHEN prev_easting IS DISTINCT FROM easting
                OR prev_northing IS DISTINCT FROM northing
                OR prev_latitude IS DISTINCT FROM latitude
                OR prev_longitude IS DISTINCT FROM longitude
              THEN 'Crime location'
            END
      
          )
        END AS updates,
        
        -- Determine whether the crime version has matching results
        -- If any crime_matching_result exists for this crime version, the UI should display it as "matched".
        COALESCE(
          EXISTS (
            SELECT 1
            FROM crime_matching_result cmr
            WHERE cmr.crime_version_id = crimeVersionId
          ),
          false
        ) AS matched
      
      FROM versioned
      
      -- Results returned newest first for the UI table.
      ORDER BY ingestionDateTime DESC
    """,
    nativeQuery = true,
  )
  fun findCrimeVersionsByCrimeReference(
    crimeReference: String?,
    pageable: Pageable,
  ): Page<CrimeVersionSummaryProjection>
}
