package uk.gov.justice.digital.hmpps.electronicmonitoringcrimematchingapi.config.emailIngestion

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(EmailIngestionProperties::class)
class EmailIngestionConfig
