version: "3"
services:
  hmpps-electronic-monitoring-crime-matching-api:
    build:
      context: .
    networks:
      - hmpps
    container_name: hmpps-electronic-monitoring-crime-matching-api
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - SPRING_PROFILES_ACTIVE=local
      - ATHENA_DATABASE_NAME=test-database
      - ATHENA_OUTPUT_BUCKET=test-output-bucket-id
      - HMPPS_SQS_PROVIDER=localstack
      - HMPPS_SQS_LOCALSTACKURL=http://local-stack-aws:4566

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

  localstack:
    image: localstack/localstack:3.0
    container_name: local-stack-aws
    networks:
      - hmpps
    ports:
      - "4566:4566"
    healthcheck:
      test: 'curl localhost:4566/_localstack/init | grep -q ''"READY": true'''
      interval: 60s
      timeout: 2s
      retries: 10
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_EXECUTION_ENV=True
      - DEFAULT_REGION=eu-west-2
      - HOSTNAME_EXTERNAL=awslocal
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps:
