apiVersion: v1
kind: Secret
metadata:
  name: hmpps-electronic-monitoring-crime-matching-ui-os-maps
type: Opaque
data:
  OS_MAPS_API_KEY: UjRNQU9MVmNhaFpSR1RKUDk5WGpBZU1ER1ZHUE15bkk=
  OS_MAPS_API_SECRET: MUpMdlJaOGhIeVY0ODU5bg==