{
 "title": "HMPPS Electronic Monitoring Crime Matching Tool",
 "tags": [ "Electronic Monitoring" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "dev,preprod,prod" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Emails Received (SES)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "RuleName": "hmpps-electronic-monitoring-crime-matching-$environment"
     },
     "metricName": "Received",
     "namespace": "AWS/SES",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Total Emails Successfully Ingested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(email_ingestion_outcome_total{ingestionStatus=\"SUCCESSFUL\",namespace=\"hmpps-electronic-monitoring-crime-matching-${environment}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Emails Partially Ingested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(email_ingestion_outcome_total{ingestionStatus=\"PARTIAL\",namespace=\"hmpps-electronic-monitoring-crime-matching-${environment}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Emails Failed Ingestion",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(email_ingestion_outcome_total{ingestionStatus=\"FAILED\",namespace=\"hmpps-electronic-monitoring-crime-matching-${environment}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Police Data Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Emails Received (SES)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expression": "FILL(m1, 0)",
     "label": "Received",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Ingestions By Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (ingestionStatus) (increase(email_ingestion_outcome_total{namespace=\"hmpps-electronic-monitoring-crime-matching-${environment}\"}[$__interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Email Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-email-notifications"
     },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-email-notifications"
     },
     "metricName": "ApproximateNumberOfMessagesNotVisible",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Email DLQ Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-email-notifications-dlq"
     },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-email-notifications-dlq"
     },
     "metricName": "ApproximateNumberOfMessagesNotVisible",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Email Queue Freshness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-email-notifications"
     },
     "metricName": "ApproximateAgeOfOldestMessage",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Email DLQ Freshness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-email-notifications-dlq"
     },
     "metricName": "ApproximateAgeOfOldestMessage",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Email Queue Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-email-notifications"
     },
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-email-notifications"
     },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-email-notifications"
     },
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Email DLQ Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-email-notifications-dlq"
     },
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-email-notifications-dlq"
     },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-email-notifications-dlq"
     },
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Crime Matching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Matching Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-matching-notifications"
     },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-matching-notifications"
     },
     "metricName": "ApproximateNumberOfMessagesNotVisible",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Matching DLQ Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-matching-notifications-dlq"
     },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-matching-notifications-dlq"
     },
     "metricName": "ApproximateNumberOfMessagesNotVisible",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Matching Queue Freshness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-matching-notifications"
     },
     "metricName": "ApproximateAgeOfOldestMessage",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Matching DLQ Freshness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-matching-notifications-dlq"
     },
     "metricName": "ApproximateAgeOfOldestMessage",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Matching Queue Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-matching-notifications"
     },
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-matching-notifications"
     },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-matching-notifications"
     },
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Matching DLQ Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-matching-notifications-dlq"
     },
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-matching-notifications-dlq"
     },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "hmpps-em-probation-devs-${environment}-matching-notifications-dlq"
     },
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}