---
# Per environment values which override defaults in hmpps-electronic-monitoring-crime-matching-api/values.yaml

generic-service:
  replicaCount: 2

  serviceAccountName: "hmpps-em-crime-matching-preprod"

  ingress:
    host: electronic-monitoring-crime-matching-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    ATHENA_OUTPUT_BUCKET: "s3://emds-preprod-athena-query-results-20241105110923178000000003"
    ATHENA_WORKGROUP: "443370694497-default"
    MFA_REQUIRED: "false"
    DATASTORE_DATABASE: "acquisitive_crime_preprod_dbt"
    FLIPT_URL: "https://feature-toggles-preprod.hmpps.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-em-crime-matching-alerts-preprod
  sqsAlertsTotalMessagesThreshold: 0
  sqsNumberAlertQueueNames:
    - hmpps-em-probation-devs-preprod-email-notifications-dlq
    - hmpps-em-probation-devs-preprod-emailsend-dlq
  rdsAlertsDatabases:
    cloud-platform-3b9e8faa7849429d: "Electronic Monitoring Crime Matching API Database"
  rdsAlertsConnectionThreshold: 65
