CREATE TABLE crime_batch
(
    id           VARCHAR(255) NOT NULL,
    police_force VARCHAR(255),
    CONSTRAINT pk_crime_batch PRIMARY KEY (id)
);

CREATE TABLE crime
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    crime_type_id        VARCHAR(255),
    crime_reference      VARCHAR(255),
    crime_date_time_from TIMESTAMP WITHOUT TIME ZONE,
    crime_date_time_to   TIMESTAMP WITHOUT TIME ZONE,
    easting              DOUBLE PRECISION,
    northing             DOUBLE PRECISION,
    latitude             DOUBLE PRECISION,
    longitude            DOUBLE PRECISION,
    datum                VARCHAR(255),
    crime_text           VARCHAR(255),
    batch_id             VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_crime PRIMARY KEY (id),
    CONSTRAINT fk_crime_batch FOREIGN KEY (batch_id) REFERENCES crime_batch(id)
);
