CREATE TABLE application_cache
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cache_name  VARCHAR(255),
    cache_key   OID,
    cache_value OID,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_application_cache PRIMARY KEY (id)
);