CREATE TABLE crime_batch
(
    id           VARCHAR(255),
    police_force VARCHAR(255),
    CONSTRAINT pk_crime_batch PRIMARY KEY (id)
);

CREATE TABLE crime
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batch_id               VARCHAR(255),
    crime_type_id          VARCHAR(255),
    crime_type_description VARCHAR(255),
    crime_reference        VARCHAR(255),
    crime_date_time_from   VARCHAR(255),
    crime_date_time_to     VARCHAR(255),
    easting                VARCHAR(255),
    northing               VARCHAR(255),
    latitude               VARCHAR(255),
    longitude              VARCHAR(255),
    datum                  VARCHAR(255),
    crime_text             VARCHAR(255),
    CONSTRAINT pk_crime PRIMARY KEY (id),
    CONSTRAINT fk_crime_batch FOREIGN KEY (batch_id) REFERENCES crime_batch(id)
);
